AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt HelloWorldTopic.TopicName
      Environment:
        Variables:
          # !Ref returns the ARN of the resource provided as argument
          SNS_TOPIC_ARN: !Ref HelloWorldTopic

  HelloWorldTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: youremail@example.com
          Protocol: email